backend:
  name: git-gateway
  branch: trunk
publish_mode: editorial_workflow
media_folder: "public/images"
public_folder: "/images"
site_url: https://lydiamichelle.art
collections:
  - name: commissions
    label: Commissions
    folder: "src/collections/commissions"
    extension: json
    create: true
    fields:
      - label: Title
        name: title
        widget: string
      - label: Medium
        name: type
        widget: string
      - label: Allow image upload
        name: allowImageUpload
        widget: boolean
      - label: Open for requests
        name: open
        widget: boolean
      - label: Additional Info
        name: additionalInfo
        widget: object
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: text }
      - label: Work Sizes
        name: workSizes
        widget: list
        fields:
          - label: Title
            name: title
            widget: string
          - label: Price Sections
            name: prices
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Value, name: value, widget: string}
  - name: series
    label: Series
    folder: "src/collections/series"
    extension: md
    create: true
    preview_path: "portfolio/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Excerpt", name: "excerpt", widget: "string" }
      - { label: "Date Published", name: "date_published", widget: "datetime" }
      - { label: "Is Published", name: "published", widget: "boolean", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: Gallery
        name: images
        widget: list
        min: 1
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Medium, name: medium, widget: string, default: "Pen and Ink" }
          - { label: Blurb, name: blurb, widget: text, required: false }
          - { label: "Work in Progress?", name: "wip", widget: boolean, default: false }
          - { label: Image, name: image, widget: image }
